CREATE TABLE billable_item
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    billable_type VARCHAR(255),
    quantity      INTEGER                                 NOT NULL,
    rate          DECIMAL                                 NOT NULL,
    total_price   DECIMAL                                 NOT NULL,
    job_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_billableitem PRIMARY KEY (id)
);

CREATE TABLE contractor
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(20)                             NOT NULL,
    last_name    VARCHAR(20)                             NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    tax_rate     DECIMAL                                 NOT NULL,
    savings_rate DECIMAL                                 NOT NULL,
    CONSTRAINT pk_contractor PRIMARY KEY (id)
);

CREATE TABLE job
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date               date                                    NOT NULL,
    address            VARCHAR(255)                            NOT NULL,
    contractor_id      BIGINT                                  NOT NULL,
    grand_total_amount DECIMAL                                 NOT NULL,
    tax_amount         DECIMAL                                 NOT NULL,
    savings_amount     DECIMAL                                 NOT NULL,
    notes              TEXT,
    CONSTRAINT pk_job PRIMARY KEY (id)
);

ALTER TABLE contractor
    ADD CONSTRAINT uc_contractor_email UNIQUE (email);

ALTER TABLE billable_item
    ADD CONSTRAINT FK_BILLABLEITEM_ON_JOB FOREIGN KEY (job_id) REFERENCES job (id);

ALTER TABLE job
    ADD CONSTRAINT FK_JOB_ON_CONTRACTOR FOREIGN KEY (contractor_id) REFERENCES contractor (id);